### ISSUE TITLE
Zoom behaviour

### ISSUE THREAD

**Issue by bravegrape** [alphagov/tech-docs-gem#101]
Current docs, for example the [GOV.UK Pay docs](https://docs.payments.service.gov.uk/#gov-uk-pay-documentation) change to mobile layout at 200% zoom (fullscreen on MacBook Air).

The docs generated with the gem that incorporates Frontend 3.1, the [test Pay docs](https://govukpay-docs-test-jfh.cloudapps.digital/#gov-uk-pay-documentation), change to mobile layout at 250% zoom.

Is this behaviour intentional or even a problem?

**Comment by jonheslop** [comment]
This must be because the design system uses different breakpoints at which is decides to show different layouts.

I imagine they changed it with good reason, so this might be a good thing. Or perhaps in the docs case it’s not 🤷‍♂

**Comment by nickcolley** [comment]
I don't think this is a problem from a user's point of view, so going to close this out for now, feel free to re-open if you think otherwise :)
