### ISSUE TITLE
Navigation is broken when deploying on a path

### ISSUE THREAD

**Issue by alex-ju** [alphagov/tech-docs-gem#128]
The left-hand side navigation doesn't look for the defined host (`host: https://alphagov.github.io/api-catalogue`) generating absolute urls from the root `/` causing broken links when deployed on GitHub pages (or to a specific folder).

Note: this only happens in a multi-page config.

**Comment by lhokktyn** [comment]
Potential fix (needs reviewing): https://github.com/alphagov/tech-docs-gem/pull/84

**Comment by alex-ju** [comment]
The `api-catalogue` is now deployed from a subdomain instead of a path. Since this is not a pain point for anyone else I'm happy to close it.
