### ISSUE TITLE
Columns in tables now display with equal widths

### ISSUE THREAD

**Issue by klssmith** [alphagov/tech-docs-gem#133]
The width of the columns in a table used to vary according to the content, but now all the columns have the same width, which can make some content appear quite squashed. @nickcolley pointed out that it seems to be related to this change https://github.com/alphagov/tech-docs-gem/commit/ffa22615851866bb7052a87285fca30273f0ac54

**Before**
![Screen Shot 2019-09-10 at 14 44 41](https://user-images.githubusercontent.com/12881990/67081892-fc7a4680-f18f-11e9-89b8-90b4608e27b9.png)

**After**
![Screen Shot 2019-09-10 at 14 44 50](https://user-images.githubusercontent.com/12881990/67081915-07cd7200-f190-11e9-8191-98ab28725a72.png)

**Comment by tombye** [comment]
Fixed in https://github.com/alphagov/tech-docs-gem/pull/154

![image](https://user-images.githubusercontent.com/87140/68768317-30734b00-061a-11ea-9b66-e6308bbd3dcc.png)
