### ISSUE TITLE
A way to write warnings/notes accessibly

### ISSUE THREAD

**Issue by ben-superdevx** [alphagov/tech-docs-gem#144]
There isn't a good way to do this at the moment. Informally we've adopted the convention of using blockquotes, but this isn't appropriate/accessible because of: 

https://www.w3.org/TR/html/grouping-content.html#the-blockquote-element

> The blockquote element represents content that is quoted from another source, optionally with a citation which must be within a footer or cite element, and optionally with in-line changes such as annotations and abbreviations.

Would it be possible to set some sort of extension on top of Markdown at the tool level, to take this convention and transform it to a specific HTML with the right classes so CSS can do the rest?

**Comment by jonathanglassman** [comment]
> I think it would be good to get examples of the content where this has been a problem.
> 
> We're now using the Design System components: https://design-system.service.gov.uk/components/warning-text/

@nickcolley Can we close this issue now that the warning component is part of the tech doc template? For example:
- docs: https://docs.cloud.service.gov.uk/get_started.html#use-cloud-foundry-api-version-3
- raw code: https://github.com/alphagov/paas-tech-docs/blob/master/source/documentation/getting_started/get_started.erb

**Comment by nickcolley** [comment]
Makes sense to me, thanks for the info :)
