### ISSUE TITLE
Anchors to h1s resolve as part of landing page URL

### ISSUE THREAD

**Issue by superdevx64** [alphagov/tech-docs-gem#145]
For example:

https://docs.registers.service.gov.uk/

resolves to:

https://docs.registers.service.gov.uk/#api-documentation-for-registers

This is fine for h2s/h3s but it's a little bit annoying for 'top' h1s (I use the term 'top' because some docs we use use multiple h1s). Could we by any chance put some sort of exception in place?

UPDATE: after multipage was introduced we now have individual h1s for pages. For example:

https://registers-docs-testing-2.cloudapps.digital/getting_updates/#getting-updates

**Comment by m-green** [comment]
I think this has been fixed as part of the accessibility fixes in v2.4.0 - links to pages no longer automatically add the h1 anchor link. I'll close this but let me know if I've missed something.
