### ISSUE TITLE
Make it easier for people to automatically deploy to the PaaS

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-gem#146]

**Comment by nickcolley** [comment]
Person from Ministry of Justice :

> "FYI, I've put together a continuous deployment process, so that we don't have to commit changes to the 'compiled' html files, after making changes to the source files.
> 
> If you're interested, it's more or less documented here:
> https://github.com/ministryofjustice/cloud-platform-user-guide/blob/master/.circleci/config.yml
> 
> It's quite specific to the way we use TDT, so I don't think it's worth submitting a PR for this, but it might be of interest if/when you get any developers working on it."

**Comment by saliceti** [comment]
This Github actions workflow automatically deploys to paas: https://github.com/DFE-Digital/technical-guidance/blob/master/.github/workflows/delete_review_app.yml
It also creates a review app for each new pull request.

**Comment by lfdebrux** [comment]
Unfortunately, [GOV.UK PaaS is being decommissioned](https://www.cloud.service.gov.uk/). In light of this, going to close this issue as won't do.
