### ISSUE TITLE
Headings following tables cause badly-nested HTML

### ISSUE THREAD

**Issue by quis** [alphagov/tech-docs-gem#147]
Test case in the before diff here: https://github.com/alphagov/notifications-tech-docs/pull/22

---

Looks like this (note the table appearing below the footer):

![image](https://user-images.githubusercontent.com/355079/38920285-d022f3c0-42ea-11e8-9f0a-e3b6f84dada8.png)

---

Due to invalid HTML, as detected by the validator:

![image](https://user-images.githubusercontent.com/355079/38920455-361a39cc-42eb-11e8-9644-bb4f5cff2daf.png)

---

Because there is no closing `</table>` tag following the `</tr>`:

![image](https://user-images.githubusercontent.com/355079/38920592-8494d5b2-42eb-11e8-80bf-077940101f5c.png)

**Comment by m-green** [comment]
I can't replicate this anymore with the suggested examples so I think it's been fixed - please reopen if I'm wrong.
