### ISSUE TITLE
v2.0.12 breaks compatibility with therubyracer, node v4

### ISSUE THREAD

**Issue by 36degrees** [alphagov/tech-docs-gem#182]
v2.0.12 bumped a load of dependencies, including bumping `middleman-autoprefixer` from 2.7 to 2.10.

`middleman-autoprefixer` 2.10 updates `autoprefixer-rails` from 8.0 to 9.1, and `autoprefixer-rails` 9.0 dropped support for `therubyracer`.

`govuk_tech_docs` doesn’t include `therubyracer` as a dependency, so I never spotted it, but several of the techs docs repos appear to include it as an additional dependency:

- alphagov/registers-tech-docs
- alphagov/prototype-kit-training
- alphagov/verify-tech-specs
- alphagov/learn-to-code
- alphagov/tdt-documentation
- hmrc/vat-roadmap

Dependabot PRs to update these repos to use v2.0.12 (like [this one](https://github.com/alphagov/prototype-kit-training/pull/28)) are generally failing with:

> ExecJS::RubyRacerRuntime is not supported. Please replace therubyracer with mini_racer in your Gemfile or use Node.js as ExecJS runtime.

It's also broken when trying to build using Node v4, as seen in alphagov/gds-way (https://github.com/alphagov/gds-way/pull/417):

> Autoprefixer doesn’t support Node v4.8.2. Update it.

**Comment by 36degrees** [comment]
Other than hmrc/vat-roadmap, most of the [instances of govuk_tech_docs and therubyracer being used together in public repos](https://github.com/search?p=2&q=govuk_tech_docs+therubyracer&type=Code) seem to be internal (in an alphagov-owned repository)

Possible options:

1) Release a new version of govuk_tech_docs that reverts middleman-autoprefixer to 8.x (we could opt to update it again in a future major version, with appropriate release notes)
2) Advise those using therubyracer to switch to using [miniracer](https://github.com/rubyjs/mini_racer) as recommended by autoprefixer-rails

**Comment by 36degrees** [comment]
@heathd has suggested that therubyracer was added to support the search functionality, but this has since (?) been re-done.

The frontend tech docs builds fine on Travis without any additional JS runtime, so assuming it also builds in other CI environments, it might be that therubyracer can now be removed from other projects entirely?

**Comment by tijmenb** [comment]
It's a bit of a mystery why those projects have added rubyracer. It seems like it was part of the middleman-search at some point:

https://github.com/alphagov/tdt-documentation/commit/1bebd05578637652d84cdf074d2485e3b6e2daa0?diff=unified#diff-e79a60dc6b85309ae70a6ea8261eaf95R122

But I can't figure out why the projects have it in their initial commit, it was never part of the template's Gemfile:

https://github.com/alphagov/tech-docs-template/commits/master/template/Gemfile

In any case, if the tests pass and site builds it should be safe to remove from Gemfiles.

**Comment by m-green** [comment]
@36degrees Do you know if this issue can be closed now? We've gone beyond v2.0.12 now so I'm wondering if we can assume everyone's solved their dependency issues?

**Comment by m-green** [comment]
Makes sense to me @lfdebrux - closing.
