### ISSUE TITLE
JQuery Version fails our dependency check

### ISSUE THREAD

**Issue by joel-stobart** [alphagov/tech-docs-gem#217]
The jQuery version used in this library is `v1.12.4` 
https://github.com/alphagov/tech-docs-gem/blob/master/lib/assets/javascripts/_vendor/jquery.js
however this is vulnerable to a couple of issues  https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-11031/version_id-286372/Jquery-Jquery-1.12.4.html

This is showing as a problem our build pipeline. 

- Joel

**Comment by lfdebrux** [comment]
[tech-docs-gem v2.4.3 with jquery v3.5.1 has been released](https://github.com/alphagov/tech-docs-gem/releases/tag/v2.4.3)  🎉 

You can upgrade with `bundle update govuk_tech_docs`.
