### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/tech-docs-gem#230]
due to https://github.com/ai/autoprefixer-rails/issues/203

project is using [middleman-autoprefixer](https://github.com/middleman/middleman-autoprefixer)

According to their [changelog](https://github.com/middleman/middleman-autoprefixer/blob/master/CHANGELOG.md), latest version is 3.0.0 which includes autoprefixer v10, but [rubygems](https://rubygems.org/gems/middleman-autoprefixer) only lists v2.10.1

**Comment by lfdebrux** [comment]
`middleman-autoprefixer` updated the changelog to mention version 3.0.0 in November 2020, but haven't released that version to rubygems or even tagged it in GitHub :/ It seems unmaintained to me, perhaps we should fork it?

**Comment by lfdebrux** [comment]
Ah, we might be able to get around it by downgrading middleman-prefixer to 2.10.0, which uses a more optimistic version spec https://github.com/middleman/middleman-autoprefixer/compare/v2.10.0...v2.10.1.

I'm trying this in #233.
