### ISSUE TITLE
Release 3.2.1 failed

### ISSUE THREAD

**Issue by timja** [alphagov/tech-docs-gem#301]
See https://github.com/alphagov/tech-docs-gem/runs/6273592550?check_suite_focus=true

latest on ruby gems
https://rubygems.org/gems/govuk_tech_docs/versions/3.2.0

At a guess the tag was pushed either manually or created by GitHub releases, but the GitHub action creates the tag itself:
https://github.com/alphagov/tech-docs-gem/blob/master/.github/workflows/publish.yaml

cc @lfdebrux

**Comment by lfdebrux** [comment]
Thanks for flagging this up. I was too quick on the draw creating the release after merging. Fixed now!
