### ISSUE TITLE
Update to support Ruby v3

### ISSUE THREAD

**Issue by TimKnight-DWP** [alphagov/tech-docs-gem#327]
## What should change

The Gem and dependencies should be updated to support Ruby v3

## User need

Ruby v2 has been end-of-life since 31-Mar-23 https://endoflife.date/ruby

**Comment by lfdebrux** [comment]
Hi @TimKnight-DWP,

Unfortunately this is blocked on support for Ruby 3.x in [Middleman](https://middlemanapp.com/), which this gem relies on.

[Support for Ruby 3.1 was recently merged to the main branch](https://github.com/middleman/middleman/pull/2635), however those changes have not yet been released to RubyGems.

**Comment by TimKnight-DWP** [comment]
@lfdebrux thanks, hopefully soon 🤞 

(sadly I am not a Ruby dev so don't feel super confident helping out otherwise I would, don't know the pitfalls )

**Comment by richardTowers** [comment]
There's now a release of Middleman with support for Ruby 3.1 - [v4.5.0](https://github.com/middleman/middleman/blob/main/CHANGELOG.md#450)

In theory, this gem should now work on Ruby 3.1, but I haven't tested it yet.

**Comment by jfharden** [comment]
Just to confirm, in [GOV.UK Pay we have just updated our tech-docs](https://github.com/alphagov/pay-tech-docs/pull/886) (which uses this gem) to ruby 3.2.2, we had to also pin HAML to < 6.

The important point being I can confirm for sure the gem works from at least version 3.3.1.
