### ISSUE TITLE
Publishing of ruby gem broken

### ISSUE THREAD

**Issue by jfharden** [alphagov/tech-docs-gem#329]
## What should change

Currently the [post-merge publishing workflow is failing](https://github.com/alphagov/tech-docs-gem/actions/runs/5023630866/jobs/9008447497) since no ruby version is specified for the ruby/setup-ruby github action.

We should either specify ruby 3.2 in the workflow file, or include a .ruby-version (or .tool-versions) file in the project root specifying 3.2.

## User need

To get the newest versions of the gem

**Comment by lfdebrux** [comment]
This has been fixed now, thanks for raising.
