### ISSUE TITLE
Header's mobile menu button briefly flashes over menu items

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/tech-docs-gem#336]
## What should change

If you have links in the header, the mobile menu button will briefly flash on wide viewports, appearing overlaid on top of the links. It should be kept hidden on wide viewports at all time.

This can be witnessed on the [Tech Docs Gem docs](https://tdt-documentation.london.cloudapps.digital/) or  [GOV.UK Developer docs](https://docs.publishing.service.gov.uk/). The following screenshot captures the overlay, noticeable in the top right corner with the text overlap and the down arrow which shouldn't be visible. (apologies in poor quality, it's been [extracted from Chrome's devtools performance recording](https://stackoverflow.com/questions/44182882/how-to-get-screenshot-from-chrome-dev-tools-performance-frame))

![menu-button-overlayed-over-menu-items](https://github.com/alphagov/tech-docs-gem/assets/396367/a1ea55bb-7397-4f58-9bb9-fb453989a1c0)

**Comment by kr8n3r** [comment]
this will likely be fixed with https://github.com/alphagov/tech-docs-gem/pull/375
