### ISSUE TITLE
Update the crown

### ISSUE THREAD

**Issue by eddgrant** [alphagov/tech-docs-gem#337]
## What should change

govuk-frontend will soon be updating the crown in https://github.com/alphagov/govuk-frontend/issues/4019. For integrity of tech-docs-gem sites, as official sources, I believe it is important to pull in this change, once it has been released.

**Comment by querkmachine** [comment]
The new Frontend releases have now been made, however the crown should only be changed after 19th February.

**Comment by davidread** [comment]
Are there plans to update the crown in the favicon?
