### ISSUE TITLE
Images with blank alt text shouldn't be wrapped in anchor tags

### ISSUE THREAD

**Issue by tombye** [alphagov/tech-docs-gem#355]
## What should change

Images with blank alt text shouldn't be wrapped in anchor tags.

## User need

All images are wrapped in anchor tags which link to the image on its own, including images with blank alt text.

When the images appear in-page, we tend to provide the information in them as text in the page. For example:

https://docs.publishing.service.gov.uk/manual/architecture-deep-dive.html

But that still leaves the link with an empty accessible name, because its contents are the image. Based on [this WCAG rule](https://www.w3.org/WAI/standards-guidelines/act/rules/c487ae/), that breaks the following success criteria:
- [2.4.4: Link purpose (in context)](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value)
- [4.1.2: Name, role, value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value)

**Comment by kr8n3r** [comment]
fixed with https://github.com/alphagov/tech-docs-gem/pull/375
