### ISSUE TITLE
inline code blocks within a link look funny

### ISSUE THREAD

**Issue by jonheslop** [alphagov/tech-docs-gem#99]
@m-green noticed that code blocks that are links look funny:

![image(1)](https://user-images.githubusercontent.com/440503/64268767-a11e2d00-cf30-11e9-9abe-a8ed087028c0.png)

You can see that here — https://govukpay-docs-test-jfh.cloudapps.digital/direct_debit/#7-call-the-api-to-check-the-status-of-the-mandate

**Comment by accessiblewebuk** [comment]
Is that because of the choice of font? Is there perhaps a better monospaced font that would work for this situation?
